/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2023-03-17 06:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1678250108118L));
    _jspx_dependants.put("jar:file:/C:/final_mission_back_end/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Stationery/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064301420000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /common/footer.jsp(4,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("context");
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
          }
          do {
            out.print(request.getContextPath());
            int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>MultiShop - Online Shop Website Template</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Channel Plugin Scripts -->\r\n");
      out.write("<script>\r\n");
      out.write("  (function() {\r\n");
      out.write("    var w = window;\r\n");
      out.write("    if (w.ChannelIO) {\r\n");
      out.write("      return (window.console.error || window.console.log || function(){})('ChannelIO script included twice.');\r\n");
      out.write("    }\r\n");
      out.write("    var ch = function() {\r\n");
      out.write("      ch.c(arguments);\r\n");
      out.write("    };\r\n");
      out.write("    ch.q = [];\r\n");
      out.write("    ch.c = function(args) {\r\n");
      out.write("      ch.q.push(args);\r\n");
      out.write("    };\r\n");
      out.write("    w.ChannelIO = ch;\r\n");
      out.write("    function l() {\r\n");
      out.write("      if (w.ChannelIOInitialized) {\r\n");
      out.write("        return;\r\n");
      out.write("      }\r\n");
      out.write("      w.ChannelIOInitialized = true;\r\n");
      out.write("      var s = document.createElement('script');\r\n");
      out.write("      s.type = 'text/javascript';\r\n");
      out.write("      s.async = true;\r\n");
      out.write("      s.src = 'https://cdn.channel.io/plugin/ch-plugin-web.js';\r\n");
      out.write("      s.charset = 'UTF-8';\r\n");
      out.write("      var x = document.getElementsByTagName('script')[0];\r\n");
      out.write("      x.parentNode.insertBefore(s, x);\r\n");
      out.write("    }\r\n");
      out.write("    if (document.readyState === 'complete') {\r\n");
      out.write("      l();\r\n");
      out.write("    } else if (window.attachEvent) {\r\n");
      out.write("      window.attachEvent('onload', l);\r\n");
      out.write("    } else {\r\n");
      out.write("      window.addEventListener('DOMContentLoaded', l, false);\r\n");
      out.write("      window.addEventListener('load', l, false);\r\n");
      out.write("    }\r\n");
      out.write("  })();\r\n");
      out.write("  ChannelIO('boot', {\r\n");
      out.write("    \"pluginKey\": \"db554ba4-b12a-4287-b247-1a88c47121aa\"\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- End Channel Plugin -->\r\n");
      out.write("    \r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"Free HTML Templates\" name=\"description\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap\" rel=\"stylesheet\">  \r\n");
      out.write("\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-light text-dark\">\r\n");
      out.write("        <div class=\"row px-xl-5 pt-5 footer-wrap mt-3\">\r\n");
      out.write("            <div class=\"col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5\">\r\n");
      out.write("                <nav class=\"navbar navbar-light bg-light\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("   <img alt=\"로고 이미지\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/GKYK_logo2.png\" style=\"width: 160px\">\r\n");
      out.write("  </a>\r\n");
      out.write("</nav>\r\n");
      out.write("                <p class=\"mb-4\">국내 최대 종합 쇼핑몰</p>\r\n");
      out.write("                <i class=\"fab fa-facebook\"></i>\r\n");
      out.write("                <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("                <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                <i class=\"fab fa-youtube\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8 col-md-12\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                        <h5 class=\"text-dark text-uppercase mb-4\">회사 안내</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start footer-detail\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>회사 소개</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>오시는 길</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                        <h5 class=\"text-dark text-uppercase mb-4\">게시판</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start footer-detail\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>공지사항</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>자유게시판</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>커뮤니티</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>상담 신청</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                        <h5 class=\"text-dark text-uppercase mb-4\">마이페이지</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start footer-detail\">\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>로그인</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>가입하기</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>고객센터</a>\r\n");
      out.write("                            <a class=\"text-dark mb-2\" href=\"#\"><i class=\"fa fa-angle-right mr-2\"></i>주문조회</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                        <h5 class=\"text-dark text-uppercase mb-4\">모바일 어플</h5>\r\n");
      out.write("                        <div class=\"d-flex flex-column justify-content-start footer-detail\">\r\n");
      out.write("                      \t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/apple.svg\" class=\"mobile-link\">\r\n");
      out.write("                      \t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/android.svg\" class=\"mobile-link\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row border-top mx-xl-5 py-4\" style=\"border-color: rgba(256, 256, 256, .1) !important;\">\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0\">\r\n");
      out.write("                <p class=\"mb-md-0 text-center text-md-left text-dark\">\r\n");
      out.write("                    &copy; <a class=\"text-primary\" href=\"#\">Domain</a>. All Rights Reserved. Designed\r\n");
      out.write("                    by\r\n");
      out.write("                    <a class=\"text-primary\" href=\"https://htmlcodex.com\">HTML Codex</a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 px-xl-0 text-center text-md-right\">\r\n");
      out.write("                <img class=\"img-fluid\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${context}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/payments.png\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-info back-to-top\"><i class=\"fa fa-angle-double-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
